import { Product } from './types';

const Products: Product[] = [
    {
        id: 1,
        title: 'Apple MacBook Pro 13"',
        brand: 'Apple',
        count: 10,
        year: 2020,
        memory: 8,
        hdd: 512,
        favorite: true,
    },
    {
        id: 2,
        title: 'Lenovo V14 ADA',
        brand: 'Lenovo',
        count: 2,
        year: 2021,
        memory: 16,
        hdd: 1024,
        favorite: false,
    },
    {
        id: 3,
        title: 'Lenovo ThinkBook 15 G2 ARE',
        brand: 'Lenovo',
        count: 4,
        year: 2019,
        memory: 32,
        hdd: 1024,
        favorite: false,
    },
    {
        id: 4,
        title: 'Lenovo Yoga Slim',
        brand: 'Lenovo',
        count: 7,
        year: 2018,
        memory: 8,
        hdd: 512,
        favorite: false,
    },
    {
        id: 5,
        title: 'Lenovo ThinkPad E15',
        brand: 'Lenovo',
        count: 8,
        year: 2020,
        memory: 16,
        hdd: 256,
        favorite: false,
    },
    {
        id: 6,
        title: 'Apple MacBook Air M1',
        brand: 'Apple',
        count: 12,
        year: 2021,
        memory: 8,
        hdd: 512,
        favorite: true,
    },
    {
        id: 7,
        title: 'Apple MacBook Pro 13"',
        brand: 'Apple',
        count: 7,
        year: 2020,
        memory: 16,
        hdd: 1024,
        favorite: false,
    },

    {
        id: 8,
        title: 'ASUS TUF Gaming A15',
        brand: 'ASUS',
        count: 6,
        year: 2020,
        memory: 8,
        hdd: 256,
        favorite: false,
    },
    {
        id: 9,
        title: 'Apple MacBook Pro 13"',
        brand: 'Apple',
        count: 2,
        year: 2020,
        memory: 32,
        hdd: 1024,
        favorite: false,
    },
    {
        id: 10,
        title: 'HP ENVY x360',
        brand: 'HP',
        count: 7,
        year: 2022,
        memory: 8,
        hdd: 256,
        favorite: false,
    },
    {
        id: 11,
        title: 'HP Pavilion Gaming 15',
        brand: 'HP',
        count: 3,
        year: 2021,
        memory: 32,
        hdd: 1024,
        favorite: true,
    },
    {
        id: 12,
        title: 'ASUS VivoBook 14',
        brand: 'ASUS',
        count: 1,
        year: 2017,
        memory: 8,
        hdd: 256,
        favorite: false,
    },
    {
        id: 13,
        title: 'ASUS ROG Strix G15',
        brand: 'ASUS',
        count: 1,
        year: 2022,
        memory: 32,
        hdd: 1024,
        favorite: false,
    },

    {
        id: 14,
        title: 'Apple MacBook Pro 14"',
        brand: 'Apple',
        count: 3,
        year: 2022,
        memory: 32,
        hdd: 1024,
        favorite: false,
    },
    {
        id: 15,
        title: 'ASUS TUF Gaming A15',
        brand: 'ASUS',
        count: 6,
        year: 2020,
        memory: 16,
        hdd: 512,
        favorite: true,
    },
    {
        id: 16,
        title: 'HP ENVY x360',
        brand: 'HP',
        count: 5,
        year: 2022,
        memory: 16,
        hdd: 512,
        favorite: true,
    },
    {
        id: 17,
        title: 'Apple MacBook Pro 14"',
        brand: 'Apple',
        count: 8,
        year: 2022,
        memory: 16,
        hdd: 512,
        favorite: true,
    },
    {
        id: 18,
        title: 'ASUS ROG Strix G15',
        brand: 'ASUS',
        count: 3,
        year: 2022,
        memory: 16,
        hdd: 1024,
        favorite: true,
    },
    {
        id: 19,
        title: 'Apple MacBook Pro 16"',
        brand: 'Apple',
        count: 2,
        year: 2022,
        memory: 16,
        hdd: 1024,
        favorite: false,
    },
    {
        id: 20,
        title: 'Lenovo ThinkBook 15 G2 ARE',
        brand: 'Lenovo',
        count: 2,
        year: 2019,
        memory: 16,
        hdd: 256,
        favorite: false,
    },
    {
        id: 21,
        title: 'ASUS VivoBook 14',
        brand: 'ASUS',
        count: 1,
        year: 2017,
        memory: 16,
        hdd: 512,
        favorite: false,
    },
    {
        id: 22,
        title: 'ASUS ZenBook 14',
        brand: 'ASUS',
        count: 7,
        year: 2020,
        memory: 8,
        hdd: 512,
        favorite: false,
    },
    {
        id: 23,
        title: 'ASUS VivoBook Flip 14',
        brand: 'ASUS',
        count: 7,
        year: 2022,
        memory: 16,
        hdd: 1024,
        favorite: true,
    },
    {
        id: 24,
        title: 'HP Omen 15',
        brand: 'HP',
        count: 2,
        year: 2021,
        memory: 32,
        hdd: 1024,
        favorite: false,
    },
];
